apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drbd-adapter
  labels:
    k8s-app: drbd-adapter
spec:
  selector:
    matchLabels:
      k8s-app: drbd-adapter
  template:
    metadata:
      labels:
        k8s-app: drbd-adapter
    spec:
      initContainers:
      - name: shipper
        image: {{ $.Values.registry }}/drbd9-shipper:{{ $.Values.drbdVersion }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        volumeMounts:
        - name: pkgs
          mountPath: /pkgs
      {{- range $.Values.distros }}
      {{ $dist := . }}
      - name: {{ $dist }}
        image: {{ $.Values.registry }}/drbd9-{{ $dist }}:{{ $.Values.drbdVersion }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        command: [ /pkgs/entrypoint.adapter.sh ]
        securityContext:
          privileged: true
        env:
        - name: LB_DROP
          value: {{ $.Values.drop | quote }}
        volumeMounts:
        {{- if regexMatch "rhel[78]" $dist }}
        - name: centos-release
          mountPath: /etc/centos-release
          readOnly: true
        {{- end }}
        - name: pkgs
          mountPath: /pkgs
        - name: os-release
          mountPath: /etc/host-release
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-local-bin
          mountPath: /usr-local-bin
        - name: etc-modules-load
          mountPath: /etc/modules-load.d
        {{- end }}
      containers:
      - name: monitor
        # Source registry: quay.io/piraeusdatastore/drbd-reactor
        image: {{ .Values.registry}}/drbd-reactor:{{ .Values.drbdReactorVersion}}
        imagePullPolicy: {{ .Values.imagePullPolicy}}
        command:
        - /usr/sbin/drbd-reactor
        - -c
        - /pkgs/drbd-reactor.toml
        volumeMounts:
        - name: pkgs
          mountPath: /pkgs
          readOnly: true
      hostNetwork: true
      terminationGracePeriodSeconds: 0
      volumes:
      - name: pkgs
        emptyDir: {}
      - name: os-release
        hostPath:
          path: /etc/os-release
      - name: centos-release
        hostPath:
          path: /etc/centos-release
      - name: usr-src
        hostPath:
          path: /usr/src    
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-local-bin
        hostPath:
          path: /usr/local/bin
      - name: etc-modules-load
        hostPath:
          path: /etc/modules-load.d
      affinity:
        nodeAffinity:
		    {{- toYaml $.Values.affinity.nodeAffinity | nindent 10 }}