apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: drbd-adapter
  labels:
    k8s-app: drbd-adapter
spec:
  selector:
    matchLabels:
      k8s-app: drbd-adapter
  template:
    metadata:
      labels:
        k8s-app: drbd-adapter
    spec:
      initContainers:
      - name: shipper
        image: {{ .Values.registry}}/drbd9-shipper:{{ .Values.drbdVersion}}
        imagePullPolicy: Always
        volumeMounts:
        - name: pkgs
          mountPath: /pkgs

      - name: rhel7
        image: {{ .Values.registry}}/drbd9-rhel7:{{ .Values.drbdVersion}}
        imagePullPolicy: Always
        command: [ /pkgs/entrypoint.adapter.sh ]
        securityContext:
          privileged: true
        env:
        - name: LB_DROP
          value: 'yes'
        volumeMounts:
        - name: centos-release
          mountPath: /etc/centos-release
          readOnly: true
        - name: pkgs
          mountPath: /pkgs
        - name: os-release
          mountPath: /etc/host-release
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-local-bin
          mountPath: /usr-local-bin
        - name: etc-modules-load
          mountPath: /etc/modules-load.d

      - name: rhel8
        image: {{ .Values.registry}}/drbd9-rhel8:{{ .Values.drbdVersion}}
        imagePullPolicy: Always
        command: [ /pkgs/entrypoint.adapter.sh ]
        securityContext:
          privileged: true
        env:
        - name: LB_DROP
          value: 'yes'
        volumeMounts:
        - name: centos-release
          mountPath: /etc/centos-release
          readOnly: true
        - name: pkgs
          mountPath: /pkgs
        - name: os-release
          mountPath: /etc/host-release
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-local-bin
          mountPath: /usr-local-bin
        - name: etc-modules-load
          mountPath: /etc/modules-load.d

      - name: bionic
        image: {{ .Values.registry}}/drbd9-bionic:{{ .Values.drbdVersion}}
        imagePullPolicy: Always
        command: [ /pkgs/entrypoint.adapter.sh ]
        securityContext:
          privileged: true
        env:
        - name: LB_DROP
          value: 'yes'
        volumeMounts:
        - name: pkgs
          mountPath: /pkgs
        - name: os-release
          mountPath: /etc/host-release
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-local-bin
          mountPath: /usr-local-bin
        - name: etc-modules-load
          mountPath: /etc/modules-load.d

      - name: focal
        image: {{ .Values.registry}}/drbd9-focal:{{ .Values.drbdVersion}}
        imagePullPolicy: Always
        command: [ /pkgs/entrypoint.adapter.sh ]
        securityContext:
          privileged: true
        env:
        - name: LB_DROP
          value: 'yes'
        volumeMounts:
        - name: pkgs
          mountPath: /pkgs
        - name: os-release
          mountPath: /etc/host-release
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-local-bin
          mountPath: /usr-local-bin
        - name: etc-modules-load
          mountPath: /etc/modules-load.d

      - name: jammy
        image: {{ .Values.registry}}/drbd9-jammy:{{ .Values.drbdVersion}}
        imagePullPolicy: Always
        command: [ /pkgs/entrypoint.adapter.sh ]
        securityContext:
          privileged: true
        env:
        - name: LB_DROP
          value: 'yes'
        volumeMounts:
        - name: pkgs
          mountPath: /pkgs
        - name: os-release
          mountPath: /etc/host-release
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-local-bin
          mountPath: /usr-local-bin
        - name: etc-modules-load
          mountPath: /etc/modules-load.d

      containers:
      - name: monitor
        image: quay.io/piraeusdatastore/drbd-reactor
        imagePullPolicy: IfNotPresent
        command:
        - tail
        - -f
        - /dev/null
        volumeMounts:
        - name: pkgs
          mountPath: /pkgs
          readOnly: true
      hostNetwork: true
      terminationGracePeriodSeconds: 0
      volumes:
      - name: pkgs
        emptyDir: {}
      - name: os-release
        hostPath:
          path: /etc/os-release
      - name: centos-release
        hostPath:
          path: /etc/centos-release
      - name: usr-src
        hostPath:
          path: /usr/src    
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-local-bin
        hostPath:
          path: /usr/local/bin
      - name: etc-modules-load
        hostPath:
          path: /etc/modules-load.d

      affinity:
        nodeAffinity:
		 {{- toYaml .Values.affinity.nodeAffinity | nindent 10 }}