{{ if eq $.Values.deployKind "job" }}
{{ range $index, $node := (lookup "v1" "Node" "" "").items }}
{{ $nodeName := $node.metadata.name }}
{{ $osImage := lower $node.status.nodeInfo.osImage }}
{{ $tag := $.Values.drbdVersion  }}
{{ $distro := "unsupported" }}
{{ if regexMatch "(red hat enterprise|centos) .*7" $osImage }}
  {{ $distro = "rhel7" }}
{{ else if regexMatch "(red hat enterprise|centos) .*8" $osImage }}
  {{ $distro = "rhel8" }}
{{ else if regexMatch "ubuntu .*18" $osImage }}
  {{ $distro = "bionic" }}
{{ else if regexMatch "ubuntu .*20" $osImage }}
  {{ $distro = "focal" }}
{{ else if regexMatch "ubuntu .*22" $osImage }}
  {{ $distro = "jammy" }}
  {{ $tag = "v9.1.11" }}
{{ end }}
{{ if and (ne $.Values.deployOnMaster "yes") (or (hasKey $node.metadata.labels "node-role.kubernetes.io/master") (hasKey $node.metadata.labels "node-role.kubernetes.io/control-plane"))}}
{{ else }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: drbd-adapter-{{ $nodeName }}-{{ $distro }}
  labels:
    app: drbd-adapter
    drbd-version: {{ $.Values.drbdVersion }}
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: drbd-adapter
        drbd-version: {{ $.Values.drbdVersion }}
    spec:
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: {{ $nodeName }}
      containers:
      - name: shipper
        image: {{ $.Values.registry }}/drbd9-shipper:{{ $tag }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        volumeMounts:
        - name: pkgs
          mountPath: /pkgs
      {{ if ne $distro "unsupported" }}
      - name: {{ $distro }}
        image: {{ $.Values.registry }}/drbd9-{{ $distro }}:{{ $tag }}
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        command: [ /pkgs/entrypoint.adapter.sh ]
        securityContext:
          privileged: true
        env:
        - name: LB_SKIP
          value: 'no'
        - name: LB_DROP
          value: 'yes'
        - name: LB_UPGRADE
          value: {{ $.Values.upgrade | quote }}
        volumeMounts:
        {{ if regexMatch "^rhel[78]$" $distro }}
        - name: centos-release
          mountPath: /etc/centos-release
          readOnly: true
        {{ end }}
        - name: pkgs
          mountPath: /pkgs
        - name: os-release
          mountPath: /etc/host-release
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
        - name: lib-modules
          mountPath: /lib/modules
        - name: usr-local
          mountPath: /usr-local
        - name: etc-drbd-conf
          mountPath: /etc/drbd.conf
        - name: etc-drbd-d
          mountPath: /etc/drbd.d
        - name: var-lib-drbd
          mountPath: /var/lib/drbd
          readOnly: true
        - name: etc-modules-load
          mountPath: /etc/modules-load.d
        - name: etc-sysconfig-modules
          mountPath: /etc/sysconfig/modules
      {{ end }}
      volumes:
      - name: pkgs
        emptyDir: {}
      - name: os-release
        hostPath:
          path: /etc/os-release
      - name: centos-release
        hostPath:
          path: /etc/centos-release
      - name: usr-src
        hostPath:
          path: /usr/src    
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-local
        hostPath:
          path: /usr/local
      - name: etc-drbd-conf
        hostPath:
          path: /etc/drbd.conf
          type: FileOrCreate
      - name: etc-drbd-d
        hostPath:
          path: /etc/drbd.d
          type: DirectoryOrCreate
      - name: var-lib-drbd
        hostPath:
          path: /var/lib/drbd
          type: DirectoryOrCreate
      - name: etc-modules-load
        hostPath:
          path: /etc/modules-load.d
      volumes:
      - name: pkgs
        emptyDir: {}
      - name: os-release
        hostPath:
          path: /etc/os-release
      - name: centos-release
        hostPath:
          path: /etc/centos-release
      - name: usr-src
        hostPath:
          path: /usr/src    
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-local
        hostPath:
          path: /usr/local
      - name: etc-drbd-conf
        hostPath:
          path: /etc/drbd.conf
          type: FileOrCreate
      - name: etc-drbd-d
        hostPath:
          path: /etc/drbd.d
          type: DirectoryOrCreate
      - name: var-lib-drbd
        hostPath:
          path: /var/lib/drbd
          type: DirectoryOrCreate
      - name: etc-modules-load
        hostPath:
          path: /etc/modules-load.d
          type: DirectoryOrCreate
      - name: etc-sysconfig-modules
        hostPath:
          path: /etc/sysconfig/modules
          type: DirectoryOrCreate
      affinity:
        nodeAffinity:
		    {{- toYaml $.Values.affinity.nodeAffinity | nindent 10 }}
{{ end }}
{{ end }}
{{ end }}