name: Release DRBD9 Images 

on:
  push:
    branches: [ "main" ]
    paths:
    - 'docker-drbd9/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'docker-drbd9/**'
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build official DRBD9 images
      run: make drbd9

    - name: Login registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push images
      run: |
        make push REG=ghcr.io/$( echo ${{ github.repository_owner }} | tr 'A-Z' 'a-z' ) IMG="rhel7 rhel8 bionic focal jammy"