on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build official DRBD9 images
      run: make drbd9

    - name: Compiling kmod-drbd for CentOS 7 stock kernels
      run: make compiler-centos7

    - name: Compiling kmod-drbd for CentOS 8 stock kernels
      run: make compiler-centos8

    - name: Build shipper image which packs kmod-drbd and static drbd-utils
      run: make shipper

    - name: Login registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push images
      run: |
        make push REG=$( echo ghcr.io/$(echo ${{ github.repository_owner }} | tr 'A-Z' 'a-z' )