name: Release Shipper Image

on:
  push:
    branches: [ "main" ]
    paths:
    - 'docker-shipper/*'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'docker-shipper/*'
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build shipper images
      run: make compiler-centos7 compiler-centos8 shipper

    - name: Login registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push images
      run: |
        make push REG=ghcr.io/$( echo ${{ github.repository_owner }} | tr 'A-Z' 'a-z' ) IMG=shipper