name: Release Chart

on:
  push:
    branches:
      - main
    paths:
      - "helm/drbd-adapter/Chart.yaml"

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1
      - name: Set env
        run: echo "GIT_ORG=$( echo ${{ github.repository_owner }} | tr 'A-Z' 'a-z' )" >> $GITHUB_ENV
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        with:
          charts_dir: helm
          charts_repo_url: https://${GIT_ORG}.github.io/drbd-adapter
          config: helm/.cr/config.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Merge index.yaml
        env:
          SSH_ID: ${{ secrets.GH_PAGES_DEPLOY }}
        run: |
          sudo snap install yq
          mkdir -vp ~/.ssh
          echo "${{SSH_ID}}" > ~/.ssh/id_gitaction
          cat ~/.ssh/id_gitaction
          cd
          pwd
          ls -1
          git clone -n git@github.com:${GIT_ORG}/hwameistor.git
          cd hwameistor
          git checkout gh-pages
          ls -1
          sleep 10
          curl https://raw.githubusercontent.com/${GIT_ORG}/hwameistor/gh-pages/index.yaml > hms.yaml
          curl https://raw.githubusercontent.com/${GIT_ORG}/drbd-adapter/gh-pages/index.yaml > dra.yaml
          yq eval-all '. as $item ireduce ({}; . * $item)' hms.yaml dra.yaml > index.yaml
          cat index.yaml
          rm -vf hms.yaml dra.yaml
          git add -A .
          git commit -m 'Update index.yaml with the latest drbd-adapter release'
          git push